
spring:
  application:
    name: image-stretching
  datasource:
    url: jdbc:mysql://172.19.9.94:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver


server:
  port: 9001
  zuul:
    url: zuul

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://docker:9999/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      biancheng: zhangsan
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
