
spring:
  application:
    name: eureka-hello

server:
  port: 8900
  zuul:
    url: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.19.9.192:30002/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      biancheng: zhangsan
    prefer-ip-address: true
    # status-page-url: http://docker:20000/eurekaHello/swagger-ui.html
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
swagger:
  enable: true
ribbon:
  eureka:
    enabled: true
    
global:
  count: 5
