linux:
  username:
    root
  password:
    root
  host:
    172.19.9.173
  port:
    22
windows:
  host:
    172.19.9.128
  port:
    9090
linuxtwo:
  username:
    cetc54
  password:
    Windows2000!
  host:
    172.19.9.126
  port:
    22
    
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://docker:9999/eureka/
    healthcheck:
      enabled: true
  instance:
    metadataMap:
      biancheng: wumeng
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6

httpactiviti: 'http://172.19.9.192:30099/antelope'

